### ISSUE TITLE
Missing PNG0.zip

### ISSUE THREAD

**Issue by vinthony** [Visillect/CubePlusPlus#1]
Hi, thanks for your awesome work!

I have downloaded the PNG1 to PNG9 file.

However, all the images are 4362 other than 4890 images.

It is source_CR2_0.zip in the files so I guess there might be PNG0.zip in Cube++.

Looking forward to your reply!

**Comment by savfod** [comment]
Oh, thank you! 
Looks like we have an error here, we'll try to fix it ASAP.

As a workaround, the missing file can be downloaded from the ftp mirror 
```wget ftp://vis.iitp.ru/Cube++/PNG0.zip```

**Comment by vinthony** [comment]
Your solution works fine.

Thanks a lot!
